/*
Most Lucrative Products

You have been asked to find the 5 most lucrative products in terms of total revenue for the first half of 2022 (from January to June inclusive).

Output their IDs and the total revenue.

Step-by-Step Approach to Retrieve Most Lucrative Products:

1. **Understand the Problem**:
   We need to calculate the total revenue generated by each product from online orders during the first half of 2022 and identify the top 5 products based on this revenue.

2. **Identify the Table**:
   - `online_orders`: This table contains details about each order, including the product ID, cost, and units sold.

3. **Calculate Total Revenue**:
   Total revenue for each product can be calculated by multiplying the `cost_in_dollars` by `units_sold`.

4. **Filter by Date**:
   We will filter the records to include only those from January 1, 2022, to June 30, 2022.

5. **Group and Sort the Results**:
   We will group the results by `product_id`, sum the total revenue, and then sort the results in descending order to get the top 5 products.

SQL Query:
*/

SELECT 
    product_id,
    SUM(cost_in_dollars * units_sold) AS total_revenue
FROM 
    online_orders
WHERE 
    date >= '2022-01-01' AND date <= '2022-06-30'
GROUP BY 
    product_id
ORDER BY 
    total_revenue DESC
LIMIT 5;
